# Generated by Django 5.1.7 on 2025-03-18 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MeshNode",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("id_str", models.CharField(max_length=9)),
                ("macaddr", models.CharField(blank=True, max_length=20, null=True)),
                ("hw_model", models.CharField(blank=True, max_length=50, null=True)),
                ("public_key", models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DeviceMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logged_time", models.DateTimeField()),
                ("battery_level", models.IntegerField()),
                ("voltage", models.FloatField()),
                ("channel_utilization", models.FloatField()),
                ("air_util_tx", models.FloatField()),
                ("uptime_seconds", models.IntegerField()),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_metrics_list",
                        to="NodeDB.meshnode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device metrics",
                "verbose_name_plural": "Device metrics",
            },
        ),
        migrations.CreateModel(
            name="MeshUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("long_name", models.CharField(max_length=50)),
                ("short_name", models.CharField(max_length=5)),
                (
                    "node",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to="NodeDB.meshnode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logged_time", models.DateTimeField()),
                ("reported_time", models.DateTimeField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("altitude", models.FloatField()),
                (
                    "location_source",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position_list",
                        to="NodeDB.meshnode",
                    ),
                ),
            ],
        ),
    ]
