---

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    # TODO: always change these in a real working environment
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./deploy/docker/initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - bot_net

  migrations:
    build:
      context: .
      dockerfile: Dockerfile-migrations
    container_name: meshtastic-migrations
    restart: no
    environment:
      POSTGRES_DB: meshtastic
      POSTGRES_USER: meshtastic
      POSTGRES_PASSWORD: meshtastic
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    depends_on:
      - postgres
    networks:
      - bot_net

  meshtastic-bot-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meshtastic-bot-manager
    restart: unless-stopped
    environment:
      DEBUG: true
      POSTGRES_DB: meshtastic
      POSTGRES_USER: meshtastic
      POSTGRES_PASSWORD: meshtastic
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      ALLOWED_HOSTS: meshtastic-bot-manager
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - bot_net

volumes:
  pg_data:

networks:
  bot_net:
