# Generated by Django 5.1.7 on 2025-03-18 22:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RawPacket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("packet_id", models.BigIntegerField()),
                ("from_int", models.BigIntegerField()),
                ("from_str", models.CharField(max_length=9)),
                ("to_int", models.BigIntegerField()),
                ("to_str", models.CharField(max_length=9)),
                ("channel", models.SmallIntegerField(null=True)),
                ("decoded_data", models.JSONField()),
                ("portnum", models.CharField(max_length=50)),
                ("hop_limit", models.SmallIntegerField()),
                ("hop_start", models.SmallIntegerField(null=True)),
                ("rx_time", models.DateTimeField()),
                ("rx_rssi", models.FloatField(null=True)),
                ("rx_snr", models.FloatField(null=True)),
                ("relay_node", models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="EncryptedPacket",
            fields=[
                (
                    "rawpacket_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="PacketLogging.rawpacket",
                    ),
                ),
                ("encrypted_data", models.TextField()),
            ],
            bases=("PacketLogging.rawpacket",),
        ),
        migrations.CreateModel(
            name="MessagePacket",
            fields=[
                (
                    "rawpacket_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="PacketLogging.rawpacket",
                    ),
                ),
                ("message_text", models.TextField()),
            ],
            bases=("PacketLogging.rawpacket",),
        ),
        migrations.CreateModel(
            name="NodeInfoPacket",
            fields=[
                (
                    "rawpacket_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="PacketLogging.rawpacket",
                    ),
                ),
                ("user_data", models.JSONField()),
            ],
            bases=("PacketLogging.rawpacket",),
        ),
        migrations.CreateModel(
            name="PositionPacket",
            fields=[
                (
                    "rawpacket_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="PacketLogging.rawpacket",
                    ),
                ),
                ("position_data", models.JSONField()),
            ],
            bases=("PacketLogging.rawpacket",),
        ),
        migrations.CreateModel(
            name="TelemetryPacket",
            fields=[
                (
                    "rawpacket_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="PacketLogging.rawpacket",
                    ),
                ),
                ("device_metrics_data", models.JSONField()),
                ("time", models.DateTimeField()),
            ],
            bases=("PacketLogging.rawpacket",),
        ),
    ]
