# Generated by Django 5.1.7 on 2025-03-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PacketLogging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawpacket',
            name='decoded_data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='rawpacket',
            name='from_str',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='rawpacket',
            name='hop_limit',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rawpacket',
            name='portnum',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rawpacket',
            name='to_int',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rawpacket',
            name='to_str',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
