# Generated by Django 5.1.7 on 2025-03-20 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PacketLogging', '0002_alter_rawpacket_decoded_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReplyPacket',
            fields=[
                ('messagepacket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PacketLogging.messagepacket')),
                ('reply_packet_id', models.BigIntegerField()),
                ('emoji', models.CharField(max_length=2, null=True)),
                ('original_message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_to', to='PacketLogging.messagepacket')),
            ],
            bases=('PacketLogging.messagepacket',),
        ),
    ]
