# Generated by Django 5.1.7 on 2025-03-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PacketLogging", "0003_messagereplypacket"),
    ]

    operations = [
        migrations.AddField(
            model_name="telemetrypacket",
            name="local_stats_data",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="telemetrypacket",
            name="device_metrics_data",
            field=models.JSONField(null=True),
        ),
    ]
