# Generated by Django 5.1.7 on 2025-03-24 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PacketLogging", "0004_telemetrypacket_local_stats_data_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseTelemetryPacket",
            fields=[
                (
                    "rawpacket_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="PacketLogging.rawpacket",
                    ),
                ),
                ("time", models.DateTimeField()),
            ],
            bases=("PacketLogging.rawpacket",),
        ),
        migrations.RemoveField(
            model_name="telemetrypacket",
            name="local_stats_data",
        ),
        migrations.AlterField(
            model_name="telemetrypacket",
            name="device_metrics_data",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="DeviceMetricsPacket",
            fields=[
                (
                    "basetelemetrypacket_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="PacketLogging.basetelemetrypacket",
                    ),
                ),
                ("batteryLevel", models.FloatField()),
                ("voltage", models.FloatField()),
                ("channelUtilization", models.FloatField()),
                ("airUtilTx", models.FloatField()),
                ("uptimeSeconds", models.BigIntegerField()),
            ],
            bases=("PacketLogging.basetelemetrypacket",),
        ),
        migrations.CreateModel(
            name="LocalStatsPacket",
            fields=[
                (
                    "basetelemetrypacket_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="PacketLogging.basetelemetrypacket",
                    ),
                ),
                ("uptimeSeconds", models.BigIntegerField()),
                ("channelUtilization", models.FloatField()),
                ("airUtilTx", models.FloatField()),
                ("numPacketsTx", models.BigIntegerField()),
                ("numPacketsRx", models.BigIntegerField()),
                ("numPacketsRxBad", models.BigIntegerField()),
                ("numOnlineNodes", models.IntegerField()),
                ("numTotalNodes", models.IntegerField()),
                ("numRxDupe", models.BigIntegerField()),
            ],
            bases=("PacketLogging.basetelemetrypacket",),
        ),
    ]
