# Generated by Django 5.1.7 on 2025-03-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PacketLogging", "0005_basetelemetrypacket_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicemetricspacket",
            name="airUtilTx",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="devicemetricspacket",
            name="batteryLevel",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="devicemetricspacket",
            name="channelUtilization",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="devicemetricspacket",
            name="uptimeSeconds",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="devicemetricspacket",
            name="voltage",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="localstatspacket",
            name="airUtilTx",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="localstatspacket",
            name="channelUtilization",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="localstatspacket",
            name="numOnlineNodes",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="localstatspacket",
            name="numPacketsRx",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="localstatspacket",
            name="numPacketsRxBad",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="localstatspacket",
            name="numPacketsTx",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="localstatspacket",
            name="numRxDupe",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="localstatspacket",
            name="numTotalNodes",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="localstatspacket",
            name="uptimeSeconds",
            field=models.BigIntegerField(null=True),
        ),
    ]
