# Generated by Django 5.1.7 on 2025-03-27 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PacketLogging', '0006_alter_devicemetricspacket_airutiltx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentMetricsPacket',
            fields=[
                ('basetelemetrypacket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PacketLogging.basetelemetrypacket')),
                ('temperature', models.FloatField(null=True)),
                ('relativeHumidity', models.FloatField(null=True)),
                ('barometricPressure', models.FloatField(null=True)),
                ('gasResistance', models.FloatField(null=True)),
                ('iaq', models.FloatField(null=True)),
            ],
            bases=('PacketLogging.basetelemetrypacket',),
        ),
    ]
