# Generated by Django 5.1.7 on 2025-03-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PacketLogging', '0007_environmentmetricspacket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedpacket',
            name='encrypted_data',
            field=models.TextField(blank=True),
        ),
    ]
