# Generated by Django 5.1.8 on 2025-04-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PacketLogging', '0008_alter_encryptedpacket_encrypted_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagereplypacket',
            name='emoji',
            field=models.CharField(db_index=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='messagereplypacket',
            name='reply_packet_id',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='rawpacket',
            name='channel',
            field=models.SmallIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawpacket',
            name='from_int',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='rawpacket',
            name='packet_id',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='rawpacket',
            name='rx_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='rawpacket',
            name='to_int',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
    ]
